---
title: "Agglometative Hierarchical Clustering for Water Chemistry by Site"
author: 'Margaret Hammond'
date: '2/16/2022'
output: 
  html_document:
    theme: flatly
    code_folding: hide
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(here)
library(janitor)
library(tidyverse)
library(palmerpenguins)
library(NbClust)
library(cluster)
library(factoextra)
library(dendextend)
library(ggdendro)
```

### Summary
**3-4 sentences that helps the audience understand the data and what you'll be exploring**

### Wrangle the Data

```{r}
chem_sbr <- read_csv(here('data', 'sbc_lter_registered_stream_chemistry.csv')) %>% 
  clean_names() %>% 
  na_if(-999) %>% 
  select(-timestamp_local)
  
```



### Citation
Citation: Santa Barbara Coastal LTER and J. Melack. 2019. SBC LTER: Land: Stream chemistry in the Santa Barbara Coastal drainage area, ongoing since 2000 ver 16. Environmental Data Initiative. https://doi.org/10.6073/pasta/67a558a24ceed9a0a5bf5e46ab841174. 
